# Site settings
title: Thinkers Journey
description: >-
  Thinking about thinking
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://arjunnair1997.github.io"
twitter_username: bananabrick2
github_username:  arjunnair1997

# Build settings
theme: minima
plugins:
  - jekyll-feed